// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwfqrehcliowhkssmkhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3ZnFyZWhjbGlvd2hrc3Nta2h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjkwMDEsImV4cCI6MjA2ODg0NTAwMX0.9WLk2hXk50jWaKWmzzeea1eifjCxfNNZYPV_kRkZT3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});